import { Verb } from "@/app/types/verb";

export const verbs: Verb[] = [
  {
    name: "Arise",
    past: "Arose",
    pastParticiple: "Arisen",
    meaning: ["Levantarse", "Surgir"],
  },
  {
    name: "Awake",
    past: "Awoke",
    pastParticiple: "Awoken",
    meaning: ["Despertar(se)"],
  },
  {
    name: "Be",
    past: "Was / Were",
    pastParticiple: "Been",
    meaning: ["Ser", "Estar"],
  },
  {
    name: "Bear",
    past: "Bore",
    pastParticiple: "Born",
    meaning: ["Soportar", "Dar a luz"],
  },
  {
    name: "Beat",
    past: "Beat",
    pastParticiple: "Beaten",
    meaning: ["Golpear"],
  },
  {
    name: "Become",
    past: "Became",
    pastParticiple: "Become",
    meaning: ["Llegar a ser"],
  },
  {
    name: "Begin",
    past: "Began",
    pastParticiple: "Begun",
    meaning: ["Empezar"],
  },
  {
    name: "Bend",
    past: "Bent",
    pastParticiple: "Bent",
    meaning: ["Doblar"],
  },
  {
    name: "Bet",
    past: "Bet",
    pastParticiple: "Bet",
    meaning: ["Apostar"],
  },
  {
    name: "Bind",
    past: "Bound",
    pastParticiple: "Bound",
    meaning: ["Atar", "Encuadernar"],
  },
  {
    name: "Bid",
    past: "Bid",
    pastParticiple: "Bid",
    meaning: ["Pujar"],
  },
  {
    name: "Bite",
    past: "Bit",
    pastParticiple: "Bitten",
    meaning: ["Morder"],
  },
  {
    name: "Bleed",
    past: "Bled",
    pastParticiple: "Bled",
    meaning: ["Sangrar"],
  },
  {
    name: "Blow",
    past: "Blew",
    pastParticiple: "Blown",
    meaning: ["Soplar"],
  },
  {
    name: "Break",
    past: "Broke",
    pastParticiple: "Broken",
    meaning: ["Romper"],
  },
  {
    name: "Breed",
    past: "Bred",
    pastParticiple: "Bred",
    meaning: ["Criar"],
  },
  {
    name: "Bring",
    past: "Brought",
    pastParticiple: "Brought",
    meaning: ["Traer", "Llevar"],
  },
  {
    name: "Broadcast",
    past: "Broadcast",
    pastParticiple: "Broadcast",
    meaning: ["Radiar"],
  },
  {
    name: "Build",
    past: "Built",
    pastParticiple: "Built",
    meaning: ["Edificar"],
  },
  {
    name: "Burn",
    past: "Burnt",
    pastParticiple: "Burnt",
    meaning: ["Quemar"],
  },
  {
    name: "Burst",
    past: "Burst",
    pastParticiple: "Burst",
    meaning: ["Reventar"],
  },
  {
    name: "Buy",
    past: "Bought",
    pastParticiple: "Bought",
    meaning: ["Comprar"],
  },
  {
    name: "Cast",
    past: "Cast",
    pastParticiple: "Cast",
    meaning: ["Arrojar"],
  },
  {
    name: "Catch",
    past: "Caught",
    pastParticiple: "Caught",
    meaning: ["Coger"],
  },
  {
    name: "Come",
    past: "Came",
    pastParticiple: "Come",
    meaning: ["Venir"],
  },
  {
    name: "Cost",
    past: "Cost",
    pastParticiple: "Cost",
    meaning: ["Costar"],
  },
  {
    name: "Cut",
    past: "Cut",
    pastParticiple: "Cut",
    meaning: ["Cortar"],
  },
  {
    name: "Choose",
    past: "Chose",
    pastParticiple: "Chosen",
    meaning: ["Elegir"],
  },
  {
    name: "Cling",
    past: "Clung",
    pastParticiple: "Clung",
    meaning: ["Agarrarse"],
  },
  {
    name: "Creep",
    past: "Crept",
    pastParticiple: "Crept",
    meaning: ["Arrastrarse"],
  },
  {
    name: "Deal",
    past: "Dealt",
    pastParticiple: "Dealt",
    meaning: ["Tratar"],
  },
  {
    name: "Dig",
    past: "Dug",
    pastParticiple: "Dug",
    meaning: ["Cavar"],
  },
  {
    name: "Do (Does)",
    past: "Did",
    pastParticiple: "Done",
    meaning: ["Hacer"],
  },
  {
    name: "Draw",
    past: "Drew",
    pastParticiple: "Drawn",
    meaning: ["Dibujar"],
  },
  {
    name: "Dream",
    past: "Dreamt / Dreamed",
    pastParticiple: "Dreamt / Dreamed",
    meaning: ["Soñar"],
  },
  {
    name: "Drink",
    past: "Drank",
    pastParticiple: "Drunk",
    meaning: ["Beber"],
  },
  {
    name: "Drive",
    past: "Drove",
    pastParticiple: "Driven",
    meaning: ["Conducir"],
  },
  {
    name: "Eat",
    past: "Ate",
    pastParticiple: "Eaten",
    meaning: ["Comer"],
  },
  {
    name: "Fall",
    past: "Fell",
    pastParticiple: "Fallen",
    meaning: ["Caer"],
  },
  {
    name: "Feed",
    past: "Fed",
    pastParticiple: "Fed",
    meaning: ["Alimentar"],
  },
  {
    name: "Feel",
    past: "Felt",
    pastParticiple: "Felt",
    meaning: ["Sentir"],
  },
  {
    name: "Fight",
    past: "Fought",
    pastParticiple: "Fought",
    meaning: ["Luchar"],
  },
  {
    name: "Find",
    past: "Found",
    pastParticiple: "Found",
    meaning: ["Encontrar"],
  },
  {
    name: "Flee",
    past: "Fled",
    pastParticiple: "Fled",
    meaning: ["Huir"],
  },
  {
    name: "Fly",
    past: "Flew",
    pastParticiple: "Flown",
    meaning: ["Volar"],
  },
  {
    name: "Forbid",
    past: "Forbade",
    pastParticiple: "Forbidden",
    meaning: ["Prohibir"],
  },
  {
    name: "Forget",
    past: "Forgot",
    pastParticiple: "Forgotten",
    meaning: ["Olvidar"],
  },
  {
    name: "Forgive",
    past: "Forgave",
    pastParticiple: "Forgiven",
    meaning: ["Perdonar"],
  },
  {
    name: "Freeze",
    past: "Froze",
    pastParticiple: "Frozen",
    meaning: ["Helar"],
  },
  {
    name: "Get",
    past: "Got",
    pastParticiple: "Got / Gotten",
    meaning: ["Obtener"],
  },
  {
    name: "Give",
    past: "Gave",
    pastParticiple: "Given",
    meaning: ["Dar"],
  },
  {
    name: "Go (Goes)",
    past: "Went",
    pastParticiple: "Gone",
    meaning: ["Ir"],
  },
  {
    name: "Grow",
    past: "Grew",
    pastParticiple: "Grown",
    meaning: ["Crecer"],
  },
  {
    name: "Grind",
    past: "Ground",
    pastParticiple: "Ground",
    meaning: ["Moler"],
  },
  {
    name: "Hang",
    past: "Hung",
    pastParticiple: "Hung",
    meaning: ["Colgar"],
  },
  {
    name: "Have",
    past: "Had",
    pastParticiple: "Had",
    meaning: ["Haber", "Tener"],
  },
  {
    name: "Hear",
    past: "Heard",
    pastParticiple: "Heard",
    meaning: ["Oir"],
  },
  {
    name: "Hide",
    past: "Hid",
    pastParticiple: "Hidden",
    meaning: ["Ocultar"],
  },
  {
    name: "Hit",
    past: "Hit",
    pastParticiple: "Hit",
    meaning: ["Golpear"],
  },
  {
    name: "Hold",
    past: "Held",
    pastParticiple: "Held",
    meaning: ["Agarrar", "Celebrar"],
  },
  {
    name: "Hurt",
    past: "Hurt",
    pastParticiple: "Hurt",
    meaning: ["Herir"],
  },
  {
    name: "Keep",
    past: "Kept",
    pastParticiple: "Kept",
    meaning: ["Conservar"],
  },
  {
    name: "Know",
    past: "Knew",
    pastParticiple: "Known",
    meaning: ["Saber", "Conocer"],
  },
  {
    name: "Kneel",
    past: "Knelt",
    pastParticiple: "Knelt",
    meaning: ["Arrodillarse"],
  },
  {
    name: "Knit",
    past: "Knit",
    pastParticiple: "Knit",
    meaning: ["Tejer", "Hacer punto"],
  },
  {
    name: "Lay",
    past: "Laid",
    pastParticiple: "Laid",
    meaning: ["Poner"],
  },
  {
    name: "Lead",
    past: "Led",
    pastParticiple: "Led",
    meaning: ["Conducir"],
  },
  {
    name: "Lean",
    past: "Leant",
    pastParticiple: "Leant",
    meaning: ["Apoyarse"],
  },
  {
    name: "Leap",
    past: "Leapt",
    pastParticiple: "Leapt",
    meaning: ["Saltar"],
  },
  {
    name: "Learn",
    past: "Learnt / Learned",
    pastParticiple: "Learnt / Learned",
    meaning: ["Aprender"],
  },
];
