import { Verb } from "@/app/types/verb";

export const verbs: Verb[] = [
  {
    name: "Arise",
    past: "Arose",
    pastParticiple: "Arisen",
    meaning: ["Levantarse", "Surgir"],
  },
  {
    name: "Awake",
    past: "Awoke",
    pastParticiple: "Awoken",
    meaning: ["Despertar(se)"],
  },
  {
    name: "Be / Am / Is / Are",
    past: "Was / Were",
    pastParticiple: "Been",
    meaning: ["Ser", "Estar"],
  },
  {
    name: "Bear",
    past: "Bore",
    pastParticiple: "Born",
    meaning: ["Soportar", "Dar a luz"],
  },
  {
    name: "Beat",
    past: "Beat",
    pastParticiple: "Beaten",
    meaning: ["Golpear"],
  },
  {
    name: "Become",
    past: "Became",
    pastParticiple: "Become",
    meaning: ["Llegar a ser"],
  },
  {
    name: "Begin",
    past: "Began",
    pastParticiple: "Begun",
    meaning: ["Empezar"],
  },
  {
    name: "Bend",
    past: "Bent",
    pastParticiple: "Bent",
    meaning: ["Doblar"],
  },
  {
    name: "Bet",
    past: "Bet",
    pastParticiple: "Bet",
    meaning: ["Apostar"],
  },
  {
    name: "Bind",
    past: "Bound",
    pastParticiple: "Bound",
    meaning: ["Atar", "Encuadernar"],
  },
  {
    name: "Bid",
    past: "Bid",
    pastParticiple: "Bid",
    meaning: ["Pujar"],
  },
  {
    name: "Bite",
    past: "Bit",
    pastParticiple: "Bitten",
    meaning: ["Morder"],
  },
  {
    name: "Bleed",
    past: "Bled",
    pastParticiple: "Bled",
    meaning: ["Sangrar"],
  },
  {
    name: "Blow",
    past: "Blew",
    pastParticiple: "Blown",
    meaning: ["Soplar"],
  },
  {
    name: "Break",
    past: "Broke",
    pastParticiple: "Broken",
    meaning: ["Romper"],
  },
  {
    name: "Breed",
    past: "Bred",
    pastParticiple: "Bred",
    meaning: ["Criar"],
  },
  {
    name: "Bring",
    past: "Brought",
    pastParticiple: "Brought",
    meaning: ["Traer", "Llevar"],
  },
  {
    name: "Broadcast",
    past: "Broadcast",
    pastParticiple: "Broadcast",
    meaning: ["Radiar"],
  },
  {
    name: "Build",
    past: "Built",
    pastParticiple: "Built",
    meaning: ["Edificar"],
  },
  {
    name: "Burn",
    past: "Burnt",
    pastParticiple: "Burnt",
    meaning: ["Quemar"],
  },
  {
    name: "Burst",
    past: "Burst",
    pastParticiple: "Burst",
    meaning: ["Reventar"],
  },
  {
    name: "Buy",
    past: "Bought",
    pastParticiple: "Bought",
    meaning: ["Comprar"],
  },
  {
    name: "Cast",
    past: "Cast",
    pastParticiple: "Cast",
    meaning: ["Arrojar"],
  },
  {
    name: "Catch",
    past: "Caught",
    pastParticiple: "Caught",
    meaning: ["Coger"],
  },
  {
    name: "Come",
    past: "Came",
    pastParticiple: "Come",
    meaning: ["Venir"],
  },
  {
    name: "Cost",
    past: "Cost",
    pastParticiple: "Cost",
    meaning: ["Costar"],
  },
  {
    name: "Cut",
    past: "Cut",
    pastParticiple: "Cut",
    meaning: ["Cortar"],
  },
  {
    name: "Choose",
    past: "Chose",
    pastParticiple: "Chosen",
    meaning: ["Elegir"],
  },
  {
    name: "Cling",
    past: "Clung",
    pastParticiple: "Clung",
    meaning: ["Agarrarse"],
  },
  {
    name: "Creep",
    past: "Crept",
    pastParticiple: "Crept",
    meaning: ["Arrastrarse"],
  },
  {
    name: "Deal",
    past: "Dealt",
    pastParticiple: "Dealt",
    meaning: ["Tratar"],
  },
  {
    name: "Dig",
    past: "Dug",
    pastParticiple: "Dug",
    meaning: ["Cavar"],
  },
  {
    name: "Do (Does)",
    past: "Did",
    pastParticiple: "Done",
    meaning: ["Hacer"],
  },
  {
    name: "Draw",
    past: "Drew",
    pastParticiple: "Drawn",
    meaning: ["Dibujar"],
  },
];
