import type { Metadata } from "next";
import "./globals.css";
import { aleo } from "./fonts/fonts";
import NavBar from "./components/nav";

export const metadata: Metadata = {
  title: "Irregular Verbs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme="light">
      <body
        className={`${aleo.className} min-h-[100dvh] mx-auto max-w-[440px]`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
