import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { aleo } from "./fonts/fonts";
import NavBar from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Irregular Verbs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${aleo.className} min-h-[100dvh] mx-auto`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
